# Generated by Django 5.1.3 on 2024-11-05 20:23

import storage.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('current_waste', models.JSONField(validators=[storage.validators.WasteValidator.validate_waste_types])),
                ('max_capacity', models.JSONField(validators=[storage.validators.WasteValidator.validate_capacity])),
            ],
        ),
    ]
