# Generated by Django 5.1.3 on 2024-11-05 20:29

import storage.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='current_waste',
            field=models.JSONField(default=dict, validators=[storage.validators.WasteValidator.validate_waste_types]),
        ),
        migrations.AlterField(
            model_name='storage',
            name='max_capacity',
            field=models.JSONField(default=dict, validators=[storage.validators.WasteValidator.validate_capacity]),
        ),
    ]
