# Generated by Django 5.1.3 on 2024-11-05 20:48

import django.db.models.deletion
import storage.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_alter_storage_current_waste_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='current_waste',
            field=models.JSONField(blank=True, default=dict, validators=[storage.validators.WasteValidator.validate_waste_types]),
        ),
        migrations.AlterField(
            model_name='storage',
            name='max_capacity',
            field=models.JSONField(blank=True, default=dict, validators=[storage.validators.WasteValidator.validate_capacity]),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('waste_generated', models.JSONField(blank=True, default=dict, validators=[storage.validators.WasteValidator.validate_waste_types])),
                ('storage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.storage')),
            ],
        ),
    ]
