# Generated by Django 5.1.3 on 2024-11-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_alter_storage_current_waste_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='latitude',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='organization',
            name='longitude',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='storage',
            name='latitude',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='storage',
            name='longitude',
            field=models.IntegerField(),
        ),
    ]
