# Generated by Django 5.1.3 on 2024-11-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_alter_organization_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='organization',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='storage',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='storage',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
